version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(levelname)s: %(process)d - %(asctime)s - %(name)s - %(message)s'
    datefmt: '%m/%d/%Y %I:%M:%S %p'
handlers:
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: default
    filename: logs/acrodisam.log
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: default
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console, file]
  